program        ::= declaration* EOF 

declaration    ::= varDecl
               | statement 

statement      ::= exprStmt
               | printStmt 

exprstmt       ::=exepression ";"
printStmt      ::="print" expression ";"